// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import AppProviders from "./providers";
import { Toaster } from "sonner";
import { ThemeScript } from "@/components/theme-script";

export const metadata: Metadata = {
  title: "thecareerly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body>
        <AppProviders>{children}</AppProviders>
        <Toaster richColors position="top-center" expand />
      </body>
    </html>
  );
}
