export enum TeamRole {
  TEAM_ADMIN = "TEAM_ADMIN",
  TEAM_MEMBER = "TEAM_MEMBER",
  GUEST = "GUEST",
  INTERVIEWER = "INTERVIEWER",
  RECRUITER = "RECRUITER",
  HIRING_MANAGER = "HIRING_MANAGER",
}

export enum OrganizationRole {
  ORG_ADMIN = "ORG_ADMIN",
  BILLING_ADMIN = "BILLING_ADMIN",
}
