export enum ACTIONS {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  PUBLISH = "PUBLISH",
  DRAFT = "DRAFT",
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED",
  NEW = "NEW",
  HOLD = "HOLD",
}
