import { SelectFieldOptions } from "@/types/common";

export const EMPLOYMENT_TYPES: Readonly<SelectFieldOptions[]> = Object.freeze([
  { value: "Full-time", label: "Full-time" },
  { value: "Part-time", label: "Part-time" },
  { value: "Contract", label: "Contract" },
  { value: "Internship", label: "Internship" },
  { value: "Other", label: "Other" },
]);

export const JOB_SENIORITY: Readonly<SelectFieldOptions[]> = Object.freeze([
  { value: "Intern", label: "Intern" },
  { value: "Junior", label: "Junior" },
  { value: "Associate", label: "Associate" },
  { value: "MidLevel", label: "Mid Level" },
  { value: "Senior", label: "Senior" },
  { value: "Lead", label: "Lead" },
  { value: "Manager", label: "Manager" },
  { value: "SeniorManager", label: "Senior Manager" },
  { value: "Director", label: "Director" },
  { value: "SeniorDirector", label: "Senior Director" },
  { value: "AVP", label: "Assistant Vice President" },
  { value: "VP", label: "Vice President" },
  { value: "SVP", label: "Senior Vice President" },
  { value: "EVP", label: "Executive Vice President" },
  { value: "CLevel", label: "C-Level" },
  { value: "President", label: "President" },
  { value: "MD", label: "Managing Director" },
  { value: "Chairman", label: "Chairman" },
]);

export const FACILITY_OPTIONS = Object.freeze([
  { value: "bonus", label: "Bonus" },
  { value: "comission", label: "Comission" },
  { value: "paid-overtime", label: "Paid Overtime" },
  { value: "medical-cover", label: "Medical Cover" },
  { value: "dental-care", label: "Dental Care" },
  { value: "life-insurance", label: "Life Insurance" },
  { value: "eye-care", label: "Eye Care" },
  { value: "company-car", label: "Company Car" },
  { value: "traval-expenses", label: "Traval Expenses" },
  { value: "share-plan", label: "Share Plan" },
  { value: "flexible-working-hours", label: "Flexible Working Hours" },
  { value: "car-allowance", label: "Car Allowance" },
  { value: "subsidised-food", label: "Subsidised Food" },
  { value: "shipping/retail-discount", label: "Shipping/Retail Discount" },
  { value: "gym-membership", label: "Gym Membership" },
  { value: "education-assistance", label: "Education Assistance" },
  { value: "pension-plan", label: "Pension Plan" },
] as const);

export const ALLOWED_VIBES_TYPES: Readonly<SelectFieldOptions[]> =
  Object.freeze([
    { value: "professional", label: "Professional" },
    { value: "modern", label: "Modern" },
    { value: "minimal", label: "Minimal" },
    { value: "vibrant", label: "Vibrant" },
  ]);

export const WORK_PREFERENCE: Readonly<SelectFieldOptions[]> = Object.freeze([
  { value: "Onsite", label: "Onsite" },
  { value: "Hybrid", label: "Hybrid" },
  { value: "Remote", label: "Remote" },
]);

export const QUALIFICATION_LEVEL: Readonly<SelectFieldOptions[]> =
  Object.freeze([
    { value: "High School / O-Levels", label: "High School / O-Levels" },
    {
      value: "Vocational / Technical Training",
      label: "Vocational / Technical Training",
    },
    {
      value: "Diploma / Advanced Diploma",
      label: "Diploma / Advanced Diploma",
    },
    { value: "Associate Degree", label: "Associate Degree" },
    { value: "Bachelor’s Degree", label: "Bachelor’s Degree" },
    { value: "Master’s Degree", label: "Master’s Degree" },
    { value: "Doctorate / PhD", label: "Doctorate / PhD" },
    { value: "Post Doctorate", label: "Post Doctorate" },
    {
      value: "Professional Certification / License",
      label: "Professional Certification / License",
    },
    {
      value: "Bootcamp / Short Course Certification",
      label: "Bootcamp / Short Course Certification",
    },
  ]);

export const PAY_PERIOD: Readonly<SelectFieldOptions[]> = Object.freeze([
  { value: "Weekly", label: "Weekly" },
  { value: "Monthly", label: "Monthly" },
  { value: "Annually", label: "Annually" },
]);

export const CURRENCY_OPTIONS: Readonly<SelectFieldOptions[]> = Object.freeze([
  { value: "AED", label: "AED - United Arab Emirates Dirham" },
  { value: "AFN", label: "AFN - Afghan Afghani" },
  { value: "ALL", label: "ALL - Albanian Lek" },
  { value: "AMD", label: "AMD - Armenian Dram" },
  { value: "ANG", label: "ANG - Netherlands Antillean Guilder" },
  { value: "AOA", label: "AOA - Angolan Kwanza" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "AWG", label: "AWG - Aruban Florin" },
  { value: "AZN", label: "AZN - Azerbaijani Manat" },
  { value: "BAM", label: "BAM - Bosnia-Herzegovina Convertible Mark" },
  { value: "BBD", label: "BBD - Barbadian Dollar" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "BIF", label: "BIF - Burundian Franc" },
  { value: "BMD", label: "BMD - Bermudian Dollar" },
  { value: "BND", label: "BND - Brunei Dollar" },
  { value: "BOB", label: "BOB - Bolivian Boliviano" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "BSD", label: "BSD - Bahamian Dollar" },
  { value: "BTN", label: "BTN - Bhutanese Ngultrum" },
  { value: "BWP", label: "BWP - Botswanan Pula" },
  { value: "BYN", label: "BYN - Belarusian Ruble" },
  { value: "BZD", label: "BZD - Belize Dollar" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "CDF", label: "CDF - Congolese Franc" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "CRC", label: "CRC - Costa Rican Colón" },
  { value: "CUP", label: "CUP - Cuban Peso" },
  { value: "CVE", label: "CVE - Cape Verdean Escudo" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "DJF", label: "DJF - Djiboutian Franc" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "DOP", label: "DOP - Dominican Peso" },
  { value: "DZD", label: "DZD - Algerian Dinar" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "ERN", label: "ERN - Eritrean Nakfa" },
  { value: "ETB", label: "ETB - Ethiopian Birr" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "FJD", label: "FJD - Fijian Dollar" },
  { value: "FKP", label: "FKP - Falkland Islands Pound" },
  { value: "GBP", label: "GBP - British Pound Sterling" },
  { value: "GEL", label: "GEL - Georgian Lari" },
  { value: "GHS", label: "GHS - Ghanaian Cedi" },
  { value: "GIP", label: "GIP - Gibraltar Pound" },
  { value: "GMD", label: "GMD - Gambian Dalasi" },
  { value: "GNF", label: "GNF - Guinean Franc" },
  { value: "GTQ", label: "GTQ - Guatemalan Quetzal" },
  { value: "GYD", label: "GYD - Guyanaese Dollar" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "HNL", label: "HNL - Honduran Lempira" },
  { value: "HRK", label: "HRK - Croatian Kuna" },
  { value: "HTG", label: "HTG - Haitian Gourde" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "ILS", label: "ILS - Israeli New Shekel" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "IQD", label: "IQD - Iraqi Dinar" },
  { value: "IRR", label: "IRR - Iranian Rial" },
  { value: "ISK", label: "ISK - Icelandic Króna" },
  { value: "JMD", label: "JMD - Jamaican Dollar" },
  { value: "JOD", label: "JOD - Jordanian Dinar" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "KGS", label: "KGS - Kyrgyzstani Som" },
  { value: "KHR", label: "KHR - Cambodian Riel" },
  { value: "KMF", label: "KMF - Comorian Franc" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "KYD", label: "KYD - Cayman Islands Dollar" },
  { value: "KZT", label: "KZT - Kazakhstani Tenge" },
  { value: "LAK", label: "LAK - Lao Kip" },
  { value: "LBP", label: "LBP - Lebanese Pound" },
  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
  { value: "LRD", label: "LRD - Liberian Dollar" },
  { value: "LSL", label: "LSL - Lesotho Loti" },
  { value: "LYD", label: "LYD - Libyan Dinar" },
  { value: "MAD", label: "MAD - Moroccan Dirham" },
  { value: "MDL", label: "MDL - Moldovan Leu" },
  { value: "MGA", label: "MGA - Malagasy Ariary" },
  { value: "MKD", label: "MKD - Macedonian Denar" },
  { value: "MMK", label: "MMK - Myanmar Kyat" },
  { value: "MNT", label: "MNT - Mongolian Tugrik" },
  { value: "MOP", label: "MOP - Macanese Pataca" },
  { value: "MRU", label: "MRU - Mauritanian Ouguiya" },
  { value: "MUR", label: "MUR - Mauritian Rupee" },
  { value: "MVR", label: "MVR - Maldivian Rufiyaa" },
  { value: "MWK", label: "MWK - Malawian Kwacha" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "MZN", label: "MZN - Mozambican Metical" },
  { value: "NAD", label: "NAD - Namibian Dollar" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "NIO", label: "NIO - Nicaraguan Córdoba" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "NPR", label: "NPR - Nepalese Rupee" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "PAB", label: "PAB - Panamanian Balboa" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "PGK", label: "PGK - Papua New Guinean Kina" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "PKR", label: "PKR - Pakistani Rupee" },
  { value: "PLN", label: "PLN - Polish Złoty" },
  { value: "PYG", label: "PYG - Paraguayan Guarani" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "RSD", label: "RSD - Serbian Dinar" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "RWF", label: "RWF - Rwandan Franc" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "SCR", label: "SCR - Seychellois Rupee" },
  { value: "SDG", label: "SDG - Sudanese Pound" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "SHP", label: "SHP - Saint Helena Pound" },
  { value: "SLL", label: "SLL - Sierra Leonean Leone" },
  { value: "SOS", label: "SOS - Somali Shilling" },
  { value: "SRD", label: "SRD - Surinamese Dollar" },
  { value: "STN", label: "STN - São Tomé and Príncipe Dobra" },
  { value: "SVC", label: "SVC - Salvadoran Colón" },
  { value: "SZL", label: "SZL - Swazi Lilangeni" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "TJS", label: "TJS - Tajikistani Somoni" },
  { value: "TMT", label: "TMT - Turkmenistani Manat" },
  { value: "TND", label: "TND - Tunisian Dinar" },
  { value: "TOP", label: "TOP - Tongan Paʻanga" },
  { value: "TRY", label: "TRY - Turkish Lira" },
  { value: "TTD", label: "TTD - Trinidad and Tobago Dollar" },
  { value: "TWD", label: "TWD - New Taiwan Dollar" },
  { value: "TZS", label: "TZS - Tanzanian Shilling" },
  { value: "UAH", label: "UAH - Ukrainian Hryvnia" },
  { value: "UGX", label: "UGX - Ugandan Shilling" },
  { value: "USD", label: "USD - United States Dollar" },
  { value: "UYU", label: "UYU - Uruguayan Peso" },
  { value: "UZS", label: "UZS - Uzbekistani Som" },
  { value: "VES", label: "VES - Venezuelan Bolívar" },
  { value: "VND", label: "VND - Vietnamese Dong" },
  { value: "VUV", label: "VUV - Vanuatu Vatu" },
  { value: "WST", label: "WST - Samoan Tala" },
  { value: "XAF", label: "XAF - Central African CFA Franc" },
  { value: "XCD", label: "XCD - East Caribbean Dollar" },
  { value: "XOF", label: "XOF - West African CFA Franc" },
  { value: "XPF", label: "XPF - CFP Franc" },
  { value: "YER", label: "YER - Yemeni Rial" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "ZMW", label: "ZMW - Zambian Kwacha" },
  { value: "ZWL", label: "ZWL - Zimbabwean Dollar" },
]);
